### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pincheira** [chetan/underscore_docset#1]
Hello,

I tried to install this DocSet manually and by using the .xml but it won't show any results associated to the underscore.js DocSet.

It shows as installed on the Preferences window.

![](http://f.cl.ly/items/0A1t2E1s163q2L2E3a0a/Screen%20shot%202012-07-10%20at%206.52.19%20PM.png)

Thanks!

**Comment by chetan** [comment]
I just tried installing it using the feed URL with the latest version of Dash and it worked fine. 

Can you check in your ~/Library/Application Support/Dash/DocSets/ folder to see if the UnderscoreJS folder is getting created and UnderscoreJS.docset is downloaded there?

**Comment by pincheira** [comment]
Thanks for your reply.

Here's the folder contents:

``` bash
➤  ls ~/Library/Application\ Support/Dash/DocSets/
BackboneJS   CSS          UnderscoreJS jQuery
```

And these are the contents of the `UndercoreJS` DocSet:

``` bash
UnderscoreJS  ➤  tree
.
└── UnderscoreJS.docset
    └── Contents
        ├── Info.plist
        └── Resources
            ├── Documents
            │   └── html
            │       ├── docs
            │       │   ├── images
            │       │   │   ├── background.png
            │       │   │   └── underscore.png
            │       │   └── master.css
            │       ├── index.html
            │       └── toc.html
            ├── Nodes.xml
            ├── Tokens.xml
            ├── docSet.dsidx
            ├── docSet.mom
            ├── docSet.skidx
            ├── foo.html
            └── tokens.rb

7 directories, 13 files
```

**Comment by chetan** [comment]
This docset is now available as part of dash itself.
